<div class="sc-popup2">
    <table>
        <tbody>
        <tr>
            <td style="padding: 30px;">
                <p class="fontBig" style="text-align: left; font-size: 26px; font-style: italic; margin: 0;">Wanna know</p>
                <p class="fontBig" style="text-align: left; font-size: 70px; line-height: 1; margin: 0;">SPECIAL</p>
                <p class="fontBig" style="text-align: left; font-size: 70px; line-height: 1; font-weight: bold; margin: 0; color: #ff1176;">DISCOUNTS?</p>
                <p class="popupSmall" style="text-align: left; font-size: 24px; line-height: 1; margin: 20px 0; font-style: italic;">Enter your email & get all <br />exclusive savings & news right into your inbox!</p>
                <div style="text-align: left;"></div>
            </td>
        </tr>
        </tbody>
    </table>
</div>

