<div class="sc-popup1">
    <table
    <tbody>
    <tr>
        <td style="background-color: rgba(255, 255, 255, 0.85); padding: 20px 10px;">
            <p style="text-align: center; font-size: 20px; margin: 0;"><span
                    style="border-bottom: 1px solid silver; padding-bottom: 10px;">Subscribe to our newsletter to get exclusive coupon of:</span>
            </p>
            <p class="fontBig"
               style="text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black; font-weight: bold; font-size: 70px; color: #ffffff; text-align: center; margin-bottom: 20px;">
                -20% OFF</p>
            <div style="text-align: center;"></div>
            <div style="text-align: center;">
                <p style="font-size: 15px; margin-top: 20px;">Hurry up, the offer will expire at January 31, 2020</p>

                <div style="text-align: center;">&nbsp;</div>
                <div style="text-align: center;">&nbsp;</div>
            </div>
        </td>
    </tr>
    </tbody>
    </table>
</div>